POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"blog 2",
    "author":"Jhon Doe",
    "url":"http://localhost:3001/api/blogs"
}

###
GET http://localhost:3001/api/blogs
